### ISSUE TITLE
GK Theme Mobile Nav Bar

### ISSUE THREAD

**Issue by rasklof** [GavickPro/Portfolio-Free-WordPress-Theme#58]
Hi,

Is there a way to hide (delete) the nav bar on mobile device ? 

Kind Regards

**Comment by dziudek** [comment]
Hello,

Please try to use code like below:

```css
@media (max-width: 640px) {
   #masthead {
      display: none;
   }
}
```
