### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by lameditationguidee** [GavickPro/Portfolio-Free-WordPress-Theme#60]
I'm using GK Portfolio.
On pages and articles i choose a font for the text. It appear good on my admin panel but when i sign out or i use an other broser it is not the good font ?

**Comment by dziudek** [comment]
Hello,

Please provide an URL to your website - without it we are unable to help you with your issue.

**Comment by lameditationguidee** [comment]
Hello,

Sorry, my url website is : http://lameditationguidee.com <http://lameditationguidee.com/>
Gaël

**Comment by dziudek** [comment]
Most probably you have set a wrong Font name:

```css
body { font-family: arial }
        .site-title { font-family: arial }
```

it should be **Arial** not **arial**
